### ISSUE TITLE
Future exception was never retrieved

### ISSUE THREAD

**Issue by DarkWingMcQuack** [optinsoft/asocksimap#1]
When using this library, i get a lot of "Future exception was never retrieved" errors.

```
future: <Future finished exception=SocksError('Can not connect to imap.gmx.com:993. Server sent fewer bytes than required (0 bytes read on a total of 2 expected bytes)')>
aiosocks.errors.SocksError: Can not connect to imap.gmx.com:993. Server sent fewer bytes than required (0 bytes read on a total of 2 expected bytes)
Future exception was never retrieved
```

or

```
ConnectionResetError: [Errno 104] Connection reset by peer
Future exception was never retrieved
future: <Future finished exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.11/site-packages/aiosocks/protocols.py", line 57, in negotiate
    self._proxy_peername, self._proxy_sockname = await req
                                                 ^^^^^^^^^
  File "/home/lukas/.local/lib/python3.11/site-packages/aiosocks/protocols.py", line 281, in socks_request
    await self.authenticate()
  File "/home/lukas/.local/lib/python3.11/site-packages/aiosocks/protocols.py", line 314, in authenticate
    chosen_auth = await self.read_response(2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/lib/python3.11/site-packages/aiosocks/protocols.py", line 150, in read_response
    return (await self._stream_reader.readexactly(n))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/streams.py", line 733, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib64/python3.11/asyncio/streams.py", line 526, in _wait_for_data
    await self._waiter
  File "/usr/lib64/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Future exception was never retrieved
```

I am not entirely sure that those are futures started by this library, but maybe it is tasks created with `create_task`.

**Comment by optinsoft** [comment]
It looks like you use old aioimaplib or aiosocks. Try reinstall asocksimap (v.1.0.4), I have added min. required versions to setup.py.
